name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  GCP_PROJECT: level-storm-465209-e1
  GCP_REGION: us-central1
  GCP_RUN_SERVICE: kashtocash
  IMAGE: gcr.io/level-storm-465209-e1/kashtocash

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT }}
          install_components: 'docker'
          export_default_credentials: true

      - name: Build Docker image
        run: |
          docker build -t $IMAGE:$GITHUB_SHA .

      - name: Push Docker image to Google Container Registry
        run: |
          gcloud auth configure-docker
          docker push $IMAGE:$GITHUB_SHA

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.GCP_RUN_SERVICE }}
          image: $IMAGE:$GITHUB_SHA
          region: ${{ env.GCP_REGION }}
