name: Deploy to Cloud Run (Docker)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker to use GCP
        run: gcloud auth configure-docker

      - name: Build Docker image
        run: docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/kashtocash .

      - name: Push Docker image
        run: docker push gcr.io/${{ secrets.GCP_PROJECT }}/kashtocash

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy kashtocash \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/kashtocash \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated
